### ISSUE TITLE
Python xml parse error

### ISSUE THREAD

**Issue by ucef-said** [misterdoak/sauron#11]
I got this error stack when i try to check update on my svn project : 
`Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/fabric/main.py", line 743, in main
    *args, **kwargs
  File "/usr/local/lib/python2.7/site-packages/fabric/tasks.py", line 424, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/usr/local/lib/python2.7/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/home/sauron/sauron-master/sauron/drupal/update.py", line 39, in check_update
    info = get_module_update_info(module, version, core_version_major)
  File "/home/sauron/sauron-master/sauron/drupal/update.py", line 179, in get_module_update_info
    root = ET.fromstring(content.text.encode('ascii', 'ignore'))
  File "/usr/local/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/local/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/local/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: undefined entity &iuml;: line 12, column 1`

Thanks for you help.

**Comment by misterdoak** [comment]
Hi,

As I can see, there's an error during parsing drupal update web service response.
Can you share your contrib modules list?

Thanks

**Comment by ucef-said** [comment]
Hello,

It was a syntax error in yml config file, sorry.

Thanks for your feedback.

**Comment by ucef-said** [comment]
Got it again.

*_List of modules *_

  admin_language/  
  admin_menu/  
  better_exposed_filters/  
  better_formats/  
  blockgroup/  
  block_class/  
  bookblock/  
  book_menus/  
  captcha/  
  ckeditor/ 
  ctools/  
  custom_search/  
  date/ 
  diff/ 
  entity/  
  entityreference/  
  entity_translation/  
  entity_view_mode/ 
  eu_cookie_compliance/ 
  expire/  
  features/ 
  features_diff/  
  features_translations/  
  field_group/  
  fontello/ 
  google_analytics/ 
  i18n/ 
  i18nviews/  
  i18n_contrib/ 
  icon/ 
  imagecache_actions/  
  imagefield_crop/  
  jquery_update/  
  l10n_update/  
  less/ 
  libraries/  
  link/ 
  magic/  
  metatag/  
  module_filter/  
  pathauto/ 
  print/  
  purge/  
  revisioning/  
  scald/  
  scheduler/  
  shs/  
  similarreferences/  
  socialmedia/  
  strongarm/  
  taxonomy_field_formatter/ 
  term_search/  
  title/  
  token/  
  translated_entityreference/  
  transliteration/  
  variable/ 
  views/  
  widgets/

Thank you in advance.

**Comment by ucef-said** [comment]
Any feedback ?
